name: Build and Deploy Docker Image

on:
  push:
    tags: ['v*']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Regex matching
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.ref_name }}
          regex: 'v[0-9]+.[0-9]+.[0-9]+'

      - name: Exit if tag not matched
        if: ${{ steps.regex-match.outputs.match == '' }}
        run: |
          echo "Tag was not matched"
          exit 1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build Docker Image
        run: docker build -t docker-registry.dipsapp.com/speclarify-fe:${{ github.ref_name }} --build-arg STAGE=prod .

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: docker-registry.dipsapp.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Registry
        run: docker push docker-registry.dipsapp.com/speclarify-fe:${{ github.ref_name }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 213.239.220.237
          username: erenyogurtcu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull docker-registry.dipsapp.com/speclarify-fe:${{ github.ref_name }}
            docker stop speclarify-fe-prod || true
            docker rm speclarify-fe-prod || true
            docker run -d --name speclarify-fe-prod -p 44410:3000 \
            docker-registry.dipsapp.com/speclarify-fe:${{ github.ref_name }}
