name: Build and Deploy Docker Image

on:
  push:
    branches:
      - rc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build Docker Image
        run: docker build -t docker-registry.dipsapp.com/speclarify-fe:${{ github.sha }} --build-arg STAGE=rc .

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: docker-registry.dipsapp.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Registry
        run: docker push docker-registry.dipsapp.com/speclarify-fe:${{ github.sha }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 213.239.220.237
          username: erenyogurtcu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull docker-registry.dipsapp.com/speclarify-fe:${{ github.sha }}
            docker stop speclarify-fe-rc || true
            docker rm speclarify-fe-rc || true
            docker run -d --name speclarify-fe-rc -p 44411:3000 \
            docker-registry.dipsapp.com/speclarify-fe:${{ github.sha }}
